### ISSUE TITLE
published 0.1.0 JARs don't work

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-parallel-collections#15]
```
resolvers += "nightlies" at "https://scala-ci.typesafe.com/artifactory/scala-integrate/"
scalaVersion := "2.13.0-pre-e2a2cba"
libraryDependencies += "org.scala-lang.modules" %% "scala-parallel-collections" % "0.1.0"
```

```
Welcome to Scala 2.13.0-pre-e2a2cba (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_112).
Type in expressions for evaluation. Or try :help.

scala> import scala.collection.parallel.CollectionConverters._
import scala.collection.parallel.CollectionConverters._
error: missing or invalid dependency detected while loading class file 'CollectionConverters.class'.
Could not access type CustomParallelizable in package scala.collection,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'CollectionConverters.class' was compiled against an incompatible version of scala.collection.
```

**Comment by SethTisue** [comment]
@szeiger is it obvious to you what's going on here?

**Comment by SethTisue** [comment]
the published JAR only includes the contents of the `scala.collection.parallel` package, omitting classes like `CustomParallelizable` which are in `scala.collection` (not to mention the stuff in `scala.collection.generic`)

**Comment by SethTisue** [comment]
@szeiger is it because `OsgiKeys.exportPackage := Seq(s"scala.collection.parallel.*;version=${version.value}"),`?

related: #5

can I ask you to sort this out? I can take care of publishing 0.1.1 once some solution is in place, even if it's an interim solution

**Comment by szeiger** [comment]
Yes, the direct cause is the missing export. I'll fix that. In the long run we need to avoid the split package. It can be used with OSGi but not with Java 9 modules.

**Comment by SethTisue** [comment]
0.1.1 build log https://travis-ci.org/scala/scala-parallel-collections/builds/213641316

**Comment by SethTisue** [comment]
try again after merging https://github.com/scala/scala-parallel-collections/pull/20: https://travis-ci.org/scala/scala-parallel-collections/builds/213646937

**Comment by SethTisue** [comment]
`Your build exited with 0.` 🍺
