### ISSUE TITLE
fix Scaladoc warnings

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-parallel-collections#18]
tons of warnings spew during Scaladoc generation, e.g.

```
[warn] /home/travis/build/scala/scala-parallel-collections/core/src/main/scala/scala/collection/parallel/ParSeqLike.scala:290: Variable mayNotTerminateInf undefined in comment for method intersect in trait ParSeq
[warn]    *  @param that   the sequence of elements to intersect with.
[warn]                       ^
```

but that's just a sample.

**Comment by jiminhsieh** [comment]
@SethTisue I could not find any warnings during generating scaladoc in current master branch. I didn't go through all of warnings, but it seems you fixed most of them in https://github.com/scala/scala-parallel-collections/pull/16.

**Comment by SethTisue** [comment]
indeed! thanks for checking on it
