### ISSUE TITLE
how to support 2.12/2.13 cross-building?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-parallel-collections#22]
hey @szeiger if I need `import scala.collection.parallel.CollectionConverters._` before I can use `.par` then how are library maintainers supposed to cross-build their code in 2.12/2.13?

idea: should we add a dummy empty `scala.collection.parallel.CollectionConverters` class to Scala 2.12.2? if it has no runtime residue, doing so won't break binary compatibility as far as I can see

**Comment by retronym** [comment]
This might be a good usecase for `-Ypredef`, you could have Scala version dependent root imports.

**Comment by szeiger** [comment]
For now I would suggest to put a dummy `CollectionConverters` object into a `scala-2.12` source folder in affected projects. It's a one-line change and sbt supports it out of the box.

In the long run we'll need some compatibility library for 2.12 -> 2.13 collections migration where we can add this object.

**Comment by sjrd** [comment]
@szeiger That solution is not really acceptable: it leaks that dummy object down to other projects depending on your library. And if there are two such libraries, you now inherit from twice this dummy object on the classpath. That's too ugly to be a recommended default solution.

**Comment by sjrd** [comment]
Here is a non-leaking solution, fully source compatible across Scala versions (no need for `scala-2.12` or `scala-2.13` folders).

**CompatParColls.scala** (private to the library)
```scala
package test

private[test] object CompatParColls {
  val Converters = {
    import Compat._

    {
      import scala.collection.parallel._

      CollectionConverters
    }
  }

  object Compat {
    object CollectionConverters
  }
}
```
**Test.scala** (actual code in the library that wants to use parallel collections)
```scala
package test

import test.CompatParColls.Converters._

object Main {
  def main(args: Array[String]): Unit = {
    val argsInt = args.par.map(_.toInt)
    argsInt.foreach(println(_))
  }
}
```
Gist: https://gist.github.com/sjrd/ccc2ec61a2ccbae1eb4ee9dea004b7a5

**Comment by SethTisue** [comment]
(I'll have to return to this in about a week)

**Comment by SethTisue** [comment]
note that it's often possible to replace something like

    Vector.fill(100)(...).par

with

    collection.parallel.immutable.ParVector.fill(100)(...)

which is fully source-compatible.

**Comment by szeiger** [comment]
We should provide 2.11 & 2.12 builds with a dummy `CollectionConverters` objects. We're already using the same approach for https://github.com/scala/scala-collection-compat/

**Comment by SethTisue** [comment]
Having now gone so long without providing empty 2.11 and 2.12 artifacts, my conclusion is that there isn't much demand and people are coping fine with what they have.

**Comment by christianrua** [comment]
i am just learning this lenguage now a days, and i am doing the RockTheJVM scala course, and i want to keep following the lesson of this topic, i'm trying to use this function import scala.collection.parallel.immutable.Parvector, but as i can see, with the sbt is possible to have this library, the problem is that in mi pc i install directly the scala, and i do not now how to install this like for example a python library when you said pip install somehting?...sorry for the stupid question...thanks for any help in this issue....bye.

**Comment by SethTisue** [comment]
@christianrua I'd suggest seeking help on https://users.scala-lang.org (forum) or https://gitter.im/scala/scala (chat)
