### ISSUE TITLE
toParArray (and friends) is not accessible

### ISSUE THREAD

**Issue by gzm0** [scala/scala-parallel-collections#23]
`toParArray` cannot be called on non-parallel collections anymore, since they do not extend the `Gen`-family.

For example:

```scala
import CollectionConverters._

Seq(1, 2, 3).toParArray
```

fails to compile.

**Comment by szeiger** [comment]
They do extend `GenTraversableOnce`. You have to import `scala.collection.parallel.CollectionsHaveToParArray` to get the conversion, same as in 2.12.

We should consider moving this into `CollectionConverters` though.

**Comment by gzm0** [comment]
Hmmm... Not sure what I missed there.

In the end we worked around `toParArray` (and in the process removed some unnecessary copies). But thanks for getting back anyways.
