### ISSUE TITLE
Support for Scala Native 0.5.x

### ISSUE THREAD

**Issue by ekrich** [scala/scala-parallel-collections#262]
In order to proceed towards a stable 0.5.0 version of Scala Native, it would really help to support the RC versions. I have a dependency on this library.

Consensus has been pretty consistent that downstream will only support the new version and not 0.4.0 in addition to the new version. I don't speak directly for the community or for Scala Native in a formal sense but this is my understanding.

According to @WojciechMazur 

> It would be also a good idea to support scala-parallel-collections. These work correctly in Scala 2.12, but were removed to separate project in 2.13

**Comment by SethTisue** [comment]
PR going to 0.5.0 would be welcome
