### ISSUE TITLE
publish the Scaladoc somewhere

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-parallel-collections#27]

**Comment by SethTisue** [comment]
a possible model would be what @ashawley did over at https://github.com/scala/scala-xml/pull/273 to publish the scala-xml Scaladoc to scala.github.io

**Comment by mslinn** [comment]
Sure would be nice to be able to point students to Scaladoc for this project. The ScalaCourses.com Parallel Collections lecture update for Scala 2.13 makes awkward noises regarding the apparent lack of published Scaladoc.

Is the Scaladoc for all the other portions of Scala that have been hived out also AWOL, I wonder? If not, why not publish the Scaladoc for parallel collections there? If so, we'll need to contemplate uttering further awkward noises.

**Comment by NthPortal** [comment]
once there's a 2.13 release for this project (which there isn't yet), you should also be able to find the docs on https://www.javadoc.io. while it would certainly be nice for them to be officially published as well, the site is a good alternative while waiting.

**Comment by mslinn** [comment]
The Scaladoc for this project on javadoc.io is stale.

**Comment by SethTisue** [comment]
> The Scaladoc for this project on javadoc.io is stale

I haven't previously dealt with javadoc.io, is there something we need to do to get them to refresh...?

**Comment by NthPortal** [comment]
again, the artifact isn't published for a 2.13 non-milestone, so there's no scaladocs published *anywhere*

**Comment by sjrd** [comment]
Version 0.2.0 *is* published for 2.13 final:
https://search.maven.org/artifact/org.scala-lang.modules/scala-parallel-collections_2.13/0.2.0/jar

I use it in Scala.js too, btw.

**Comment by NthPortal** [comment]
my mistake.

you can trigger a download by javadoc.io by visiting the page where the docs ought to be

![image](https://user-images.githubusercontent.com/7505383/60637594-12364c80-9de9-11e9-8bc3-1ab7698bdee8.png)

and it is in fact already live (in about 60 seconds or so): https://www.javadoc.io/doc/org.scala-lang.modules/scala-parallel-collections_2.13/0.2.0

**Comment by mslinn** [comment]
@NthPortal Awesome! The UI for that site is non-obvious. Thanks!

**Comment by NthPortal** [comment]
I still think we should publish them officially

**Comment by julienrf** [comment]
FWIW, there is a direct link to the API documentation on https://index.scala-lang.org/scala/scala-parallel-collections/scala-parallel-collections/0.2.0

**Comment by mslinn** [comment]
Got it, thanks!

**Comment by SethTisue** [comment]
> I still think we should publish them officially

what's the advantage over letting javadoc.io do it?

**Comment by mslinn** [comment]
`javadoc.io` does not provide a facility for searching. The Scaladoc for Scala features a search box when hosted on `scala-lang.org`. If the `scala-parallel-collections` API was also published on `scala-lang.org` might it be possible to provide a similar search capability?

**Comment by NthPortal** [comment]
> what's the advantage over letting javadoc.io do it?

it's... official, I guess? also, you have to know javadoc.io exists (or that Scaladex has links to it) to use it, whereas somewhere official is where you'd expect it. idk. it's not a super strong argument

**Comment by mslinn** [comment]
In addition to not supporting search, the version that would be deployed to javadoc.io does not have links back to the main scala scaladoc

**Comment by SethTisue** [comment]
> `javadoc.io` does not provide a facility for searching. The Scaladoc for Scala features a search box when hosted on `scala-lang.org`.

I visited https://www.javadoc.io/doc/org.scala-lang.modules/scala-parallel-collections_2.13/0.2.0 and did a search using the search field at the top and it seemed to work fine? I'm not following what you mean, here.

**Comment by mslinn** [comment]
I stand corrected.

**Comment by NthPortal** [comment]
> the version that would be deployed to javadoc.io does not have links back to the main scala scaladoc

it's a little awkward to get a link to the current page, but permalinks all work, as well as middle clicking on any link on the page (or clicking "copy link address")

**Comment by mslinn** [comment]
As an example of a link that should be there but isn't, there is no link to `Map` or `MapOps` from https://static.javadoc.io/org.scala-lang.modules/scala-parallel-collections_2.13/0.2.0/scala/collection/parallel/immutable/index.html#ParMapLike[K,+V,+CC[X,Y]%3C:scala.collection.parallel.immutable.ParMap[X,Y],+Repr%3C:scala.collection.parallel.immutable.ParMapLike[K,V,scala.collection.parallel.immutable.ParMap,Repr,Sequential]withscala.collection.parallel.immutable.ParMap[K,V],+Sequential%3C:scala.collection.Map[K,V]withscala.collection.MapOps[K,V,scala.collection.Map,Sequential]]extendsParMapLike[K,V,CC,Repr,Sequential]withParIterableLike[(K,V),scala.collection.parallel.immutable.ParIterable,Repr,Sequential]

You will need to expand `ParMapLike` to see the `Map` reference.

Wow, that is a huge URL.

**Comment by NthPortal** [comment]
I actually think that that link not working is a scaladoc problem, not a problem with javadoc.io

**Comment by julienrf** [comment]
Yeah, there is an option to set when we generate the scaladoc if we want to have links to the standard library docs.

**Comment by SethTisue** [comment]
> I actually think that that link not working is a scaladoc problem, not a problem with javadoc.io

agree. opened https://github.com/scala/scala-parallel-collections/issues/73 on it

**Comment by SethTisue** [comment]
I've opened #75, which just links to javadoc.io

**Comment by SethTisue** [comment]
> I still think we should publish them officially

(not opposed, but I don't intend to tackle it, either)
