### ISSUE TITLE
Publish for 2.13.0-M2

### ISSUE THREAD

**Issue by sjrd** [scala/scala-parallel-collections#33]
I'll need this to publish the full set of Scala.js artifacts for 2.13.0-M2. ;)

No rush, those are not critical artifacts, as in they're not the ones needed by devs to use Scala.js with 2.13.0-M2.

**Comment by lrytz** [comment]
This should be very easy now, I did this:

```
git tag -s -m "1.0.2 for 2.13.0-M2" v1.0.2#2.13.0-M2#8 668044565ddeef8e6c8136824768dc2e9053955d
git push upstream v1.0.2#2.13.0-M2#8
```

Build running here: https://travis-ci.org/scala/scala-parallel-collections/builds/258465923

**Comment by lrytz** [comment]
It's on the way to central.

**Comment by sjrd** [comment]
Thanks!

**Comment by sjrd** [comment]
Uh oh. It seems you published it under version 1.0.2, whereas it should have been 0.1.2 :s

**Comment by lrytz** [comment]
😱

**Comment by lrytz** [comment]
That's quite stupid.. What could we do?
  - Keep that version, make the project 1.0.x
  - Call this one dead - there's no way to remove it from maven though, and it will conflict in the future if we move to 1.0.x
  - ???

**Comment by sjrd** [comment]
I'm afraid the first bullet is the only reasonable option. Calling that version dead would have issues with conflict resolution in the future, as it would pick 1.0.2 over 0.1.3 for example.

**Comment by lrytz** [comment]
Though the wrong `1.0.2` release is only done with binary version 2.13.0-M2. So by the time we move this project to 1.0.x, 2.13 would be out, and having this stale thing on maven would not be a practical issue.

**Comment by sjrd** [comment]
That's a good point.

**Comment by lrytz** [comment]
https://issues.sonatype.org/browse/MVNCENTRAL-842

**Comment by lrytz** [comment]
So sometimes people ask for that..

**Comment by sjrd** [comment]
I see. Maybe we could then ask for 1.0.2 to be purged, and remember somewhere that that version number should be skipped when we actually get to 1.0.x?

**Comment by lrytz** [comment]
Again, it would only be a problem if we'd want to publish the actual 1.0.2 for 2.13.0-M2, which is not going to happen. So maybe it's OK to bend the rules here. I'll wait for @SethTisue to chime in.

**Comment by SethTisue** [comment]
I think it's fine to just leave the bogus artifact out there and not worry about it, since it's M2 specific.

**Comment by lrytz** [comment]
OK, so I'm just going to push 0.1.2 for 2.13.0-M2, and we live on?

**Comment by lrytz** [comment]
Running here: https://travis-ci.org/scala/scala-parallel-collections/builds/258692986

I'm tempted to delete the bad tag, objections?

**Comment by SethTisue** [comment]
> I'm tempted to delete the bad tag, objections?

do it 🔪💀

**Comment by lrytz** [comment]
http://repo1.maven.org/maven2/org/scala-lang/modules/scala-parallel-collections_2.13.0-M2/0.1.2/
