### ISSUE TITLE
parallel operations never terminate in the REPL

### ISSUE THREAD

**Issue by julienrf** [scala/scala-parallel-collections#34]
Tested with scala 2.13.0-M1 and parallel-collections 0.1.2.

The following expression does not terminate in the REPL:

~~~ scala
(1 until 1000).par.filter(n => n % 3 == 0).count(n => n.toString == n.toString.reverse)
~~~

With 2.11.8 it terminates. With 2.12.3 it doesn’t terminate either.

However, if I put the same expression in a program its evaluation does terminate.

**Comment by retronym** [comment]
This is a consequence of the new lambda encoding:

https://stackoverflow.com/questions/15176199/scala-parallel-collection-in-object-initializer-causes-a-program-to-hang/15176433#15176433

https://github.com/scala/bug/issues/8119

`scala -Yrepl-classbased` is a workaround:

```
⚡ scala -Yrepl-class-based
Welcome to Scala 2.12.3 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_112).
Type in expressions for evaluation. Or try :help.

scala> (1 until 1000).par.filter(n => n % 3 == 0).count(n => n.toString == n.toString.reverse)
res0: Int = 36
```

However, that its own problems, so we can't make it the default. For the 2.13 REPL, we're aiming for a best-of-both-worlds solution.

**Comment by retronym** [comment]
Another workaround:

```
scala> def foo = (1 until 1000).par.filter(n => n % 3 == 0).count(n => n.toString == n.toString.reverse)
foo: Int

scala> foo
res0: Int = 36
```

**Comment by som-snytt** [comment]
Why does everyone always blame the REPL?

I hope the new REPL brings the user into a close association with the code they write: What did I enter? How was it wrapped? Let me specify its wrapped behavior. What did it compile to? Let me examine the trees per phase and the result bytecode. Let me set some breakpoints and single step so I really get it. Not to mention JIT behavior and benchmarking support.

**Comment by DarkDimius** [comment]
@retronym this is not inherent to the Java8 lambda encoding. This is simply a bug due to way how labmdalift works in Scalac. Dotty does not have this bug and does use lambdas.

Similar discussion happened here: https://github.com/rickynils/scalacheck/issues/290
Fix for this issue in Dotty: https://github.com/lampepfl/dotty/pull/628/files

**Comment by retronym** [comment]
@DarkDimius The PR you linked doesn't describe the change in enough detail for me to understand.

I've produced a [bytecode diff](https://gist.github.com/retronym/cbef29c74c630127a6e9b34ad395d45d) to contrast scalac and dotty for this test case.  Could you help connect the dots for me?

**Comment by retronym** [comment]
Okay, now I see the difference. The lambda in scalac is backed by a static method, and in dotty it is backed by an instance method for a lambda that captures `this`. Seems like a tradeoff between how deadlock prone things are vs how much additional baggage is carried around when serializing the lambda. I can see that for lambdas lexically enclosed in a modules constructor the dotty approach might a better default. What rules is applied to decide whether `static` is used?

**Comment by odersky** [comment]
I believe the criterion is which this-references the lambda contains. If it contains references to an enclosing this, it goes in the same class. if it does not contain any this references, it becomes static.

**Comment by DarkDimius** [comment]
> I believe the criterion is which this-references the lambda contains. If it contains references to an enclosing this, it goes in the same class. if it does not contain any this references, it becomes static.

There's one additional rule: it becomes static unless it's owned by a top-level module class.
