### ISSUE TITLE
publish for Scala 2.13.0-M3

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-parallel-collections#38]
I'll attempt to handle this.

**Comment by SethTisue** [comment]
tomorrow.

**Comment by SethTisue** [comment]
Travis-CI liked #39, so we know the existing code already compiles, and tests pass, on M3

we don't strictly need a 0.1.3 release for this. there is a fork-join change that should go in an eventual 0.1.3 release, but for now, I think it will be fine to just back-publish 0.1.2 for M3

**Comment by SethTisue** [comment]
`v0.1.2#2.13.0-M3#8` tag pushed. Travis-CI build: https://travis-ci.org/scala/scala-parallel-collections/builds/336322648

**Comment by SethTisue** [comment]
I hit "close" and "release" in the Sonatype web UI, so the artifacts should be on their way to Maven Central.

**Comment by xerial** [comment]
@SethTisue Have you tried sbt-sonatype? This will simplify the release process (at least you can save the time for opening the Sonatype WebUI). 
https://github.com/xerial/sbt-sonatype

Anyway, thanks for the quick work!

**Comment by SethTisue** [comment]
@xerial see https://github.com/scala/sbt-scala-module/issues/37
