### ISSUE TITLE
Reimport to preserve history?

### ISSUE THREAD

**Issue by retronym** [scala/scala-parallel-collections#4]
For other modules, we used git filter-branch to bring across the file history.

e.g. https://github.com/scala/scala-xml/commit/fb12a4085e00aed7fdacc8de535d709039ae6f64 contains the history from scala/scala.

I think we should follow the same process for this repo.

**Comment by szeiger** [comment]
How much history should we preserve? A complete `scala/scala` has 148 MB. Keeping only the history of `library/scala/collection` without `mutable` and `immutable` and removing all other branches, tags and empty commits brings it down to 3 MB which looks much more reasonable to me. @adriaanm?

**Comment by adriaanm** [comment]
I remember using filter branch on the other repos as well. Something like

```
git clone --no-hardlinks scala scala-xml
cd scala-xml
git filter-branch --index-filter filter-xml.sh --prune-empty master
git reset --hard
git gc --aggressive
git prune
git rebase <first commit> # linear history, only doing this for 2.11 (and future versions)
# find a few key commits and tag them (mostly manually using git log --grep and git describe --contains)
```

**Comment by adriaanm** [comment]
I think I'm saying the same thing as Jason, actually. We should keep the full history, but only the parts that affect the sources of the parallel collections. I used the above commands for that.

**Comment by szeiger** [comment]
So we should leave now empty commits as part of the history?

**Comment by szeiger** [comment]
History import done. I squashed the changes so far into a single commit to preserve the history of the tests, too. They were added after the original import, so their history couldn't be tracked correctly on top of the rebased commits.
