### ISSUE TITLE
support Scala 2.13.0-RC1

### ISSUE THREAD

**Issue by xuwei-k** [scala/scala-parallel-collections#41]

**Comment by lrytz** [comment]
Just to avoid duplicating work: I think @szeiger was planning to work on this.

Note that Scala.js is waiting for this (https://github.com/scala-js/scala-js/pull/3344#issuecomment-390512184)

**Comment by lrytz** [comment]
cc @biboudis

**Comment by SethTisue** [comment]
this will take some real work and might not be done until around M5 time. libraries seeking to publish for M4 should, if possible, seek workarounds rather than wait.

**Comment by xuwei-k** [comment]
https://github.com/scala/scala-parallel-collections/pull/42

**Comment by SethTisue** [comment]
this is actively being worked on by @julienrf

**Comment by SethTisue** [comment]
#42 is near the finish line

**Comment by SethTisue** [comment]
stdlib collections needed some changes to accommodate parallel collections, so we will not be able to publish for M5

**Comment by julienrf** [comment]
What were the needed changes in the stdlib?

**Comment by SethTisue** [comment]
@julienrf https://github.com/scala/scala/pull/7636

**Comment by julienrf** [comment]
Ah indeed :)

**Comment by SethTisue** [comment]
I don't think we need to leave this open. the module will be published for RC1 as part of our usual release-time rounds
