### ISSUE TITLE
scala-parallel-collections documentation

### ISSUE THREAD

**Issue by amerywu** [scala/scala-parallel-collections#51]
The documentation for this project is a bit sparse.
Would the project benefit from improved documentation, perhaps in .md format in a doc directory?
Example of documentation I have done previously:
https://github.com/amerywu/ikodaSparse/wiki

**Comment by SethTisue** [comment]
the docs are at https://docs.scala-lang.org/overviews/parallel-collections/overview.html

if that wasn't obvious, perhaps there are one or more places we should add links?
