### ISSUE TITLE
Set up publishing

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-parallel-collections#7]

**Comment by adriaanm** [comment]
Once that's done, we can get https://github.com/scala/scala/pull/5603 merged

**Comment by SethTisue** [comment]
5603 is merged — I'm working on this now

**Comment by SethTisue** [comment]
version 0.1 publishing is in progress at https://travis-ci.org/scala/scala-parallel-collections/builds/212602706 . go go go!

**Comment by SethTisue** [comment]
oops, the version number regex in admin/build.sh is picky, rightly so. deleted v0.1 tag. version 0.1.0 publishing in progress at https://travis-ci.org/scala/scala-parallel-collections/builds/212604304

**Comment by SethTisue** [comment]
sigh

```
Going to release from tag v0.1.0!
admin/secring.asc.enc: No such file or directory
140255731238560:error:02001002:system library:fopen:No such file or directory:bss_file.c:398:fopen('admin/secring.asc.enc','r')
140255731238560:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
```

I haven't set the module stuff up in a new repo before, I'll poke around...

**Comment by szeiger** [comment]
Some setup is still required (see https://github.com/scala/scala-parallel-collections/blob/master/admin/README.md). I tried to perform all these steps when I set up the new repo but they apparently had prerequisites like an already populated git repo and an existing Travis CI build, so I had to put it on hold.

**Comment by SethTisue** [comment]
I went through the steps in #13 

I pushed a new `v0.1.0` tag and the release build is in progress here: https://travis-ci.org/scala/scala-parallel-collections/builds/213142948 🤞

**Comment by SethTisue** [comment]
oh, looks like we need to disable publishing in the root project, same thing as https://github.com/typesafehub/migration-manager/issues/133 . despite the failure at the end, the artifacts we care about it did make it to Sonatype

**Comment by SethTisue** [comment]
> looks like we need to disable publishing in the root project

#14 will take care of that, with any luck

**Comment by SethTisue** [comment]
JARs are published 🍾

**Comment by SethTisue** [comment]
they don't work, though: #15
