### ISSUE TITLE
release version 1.0.0

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-parallel-collections#80]
we might as well, right?

but note that #5 / https://github.com/scala/community-build/issues/981 needs to be dealt with before doing a next release of any kind — since the sbt-scala-module/sbt-osgi upgrade that @lrytz did, our OSGi settings are making us publish an incomplete JAR

**Comment by SethTisue** [comment]
we also had OSGi trouble in scala-collection-contrib (https://github.com/scala/scala-collection-contrib/issues/51) and ended up throwing up our hands and documenting the lack of OSGI support with a "help wanted" ticket

I think we should do that here as well

**Comment by SethTisue** [comment]
@lrytz said yes, let's go 1.0

**Comment by SethTisue** [comment]
over at https://github.com/scala/scala-parallel-collections/issues/101 the possibility was raised of removing `IterableOnce` as a parent type of the parallel collections. delaying a bit longer to see if there's any further debate on that, and/or a PR. (though I feel like it's a pretty basic design choice to be revisiting this late, so my hunch is that the status quo will prevail....)

**Comment by SethTisue** [comment]
I am resuming work on this and hope to publish within the next 2 weeks or so. (scala-collection-compat is ahead of it in my queue.)

**Comment by SethTisue** [comment]
Release checklist

* [ ] Make sure community build has been testing current code
* [ ] Check for pending issues and PRs
* [ ] Check for needed version bumps build-wide
* [ ] Draft release notes
* [ ] Tag/publish
* [ ] Wait for artifacts to arrive on Maven Central
* [ ] Update version in readme
* [ ] See if readme needs any additional work
* [ ] (maybe) Publicity?

**Comment by SethTisue** [comment]
sigh, 6ebdf094561adebe76e53d57d8d2ebe7ad6870f4 is massively binary incompatible, says MiMa

if we leave it in place, we break bincompat. but if we revert it, I doubt the code can be compiled on Dotty, though I can check and see

and this has me thinking that before we go 1.0, we ought to add Dotty to the crossbuild. so I'm adding that to the steps above.

**Comment by NthPortal** [comment]
just to clarify, this will be 1.0.0 rather than 1.0, correct?

**Comment by SethTisue** [comment]
> this will be 1.0.0 rather than 1.0, correct?

yes

**Comment by SethTisue** [comment]
Dotty WIP: #113

**Comment by SethTisue** [comment]
merged Dotty PRs: #117, #118, #119, #120

then #113 finishes it off — it's ready for review

**Comment by SethTisue** [comment]
About breaking bincompat, 1) I simply don't see a way around it, but 2) I think I've managed to convince myself it isn't so bad because afaict ordinary users won't be affected, the only people who might be affected (afaict) are those who are writing their own splitters, that kind of thing — it isn't even obvious to me, for lack of detailed knowledge of the APIs, whether it's likely that even those folks would be affected in practice.

So I think I've made peace with it.

**Comment by SethTisue** [comment]
PR merged. Next step is simply to wait until Scala 3.0.0-M1 is out. Once that happens, I suppose we ought to do 1.0.0-RC1 first before going full 1.0.0.

**Comment by SethTisue** [comment]
1.0.0-RC1 release checklist

* [x] Make sure community build has been testing current code
  * https://github.com/scala/community-build/blob/2.13.x/proj/scala-parallel-collections.conf
* [x] Check for pending issues and PRs
* [x] Check for version bumps build-wide
  * https://github.com/scala/scala-parallel-collections/pull/111
* [x] Add Dotty to crossbuild
  * https://github.com/scala/scala-parallel-collections/pull/113
* [x] Wait for Scala 3.0.0-M1 to be released
* [x] Upgrade to Scala 3.0.0-M1
  * #129
* [x] Draft release notes
* [x] Tag/publish 1.0.0-RC1
  * https://github.com/scala/scala-parallel-collections/releases/tag/v1.0.0-RC1
  * https://travis-ci.com/github/scala/scala-parallel-collections/builds/198361751
* [ ] Wait for artifacts to arrive on Maven Central
  * https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parallel-collections_2.13/1.0.0-RC1/
  * https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parallel-collections_3.0.0-M1/1.0.0-RC1/
* [ ] Update version in readme
* [ ] See if readme needs any additional work
* [ ] Enable MiMa
* [ ] Add to Scala 3 community build
* [ ] (maybe) Publicity?
* [ ] Send experience report to Adrien, as per https://contributors.scala-lang.org/t/scala-3-migration-guide-continuation/4444/4
* [ ] Wait for feedback on the RC
* [ ] Repeat above for 1.0.0

**Comment by SethTisue** [comment]
1.0.0-RC1 is published

https://twitter.com/SethTisue/status/1324159849387581441

**Comment by SethTisue** [comment]
1.0.0 release checklist

* [ ] Tag/publish 1.0.0
* [ ] Wait for artifacts to arrive on Maven Central
* [ ] Update version in readme
* [ ] Bump MiMa reference version
* [ ] Publicity?

**Comment by SethTisue** [comment]
IT IS DONE
