### ISSUE TITLE
OSGi `-split-package:=first` seems unsafe

### ISSUE THREAD

**Issue by lrytz** [scala/scala-parallel-collections#97]
I took the current `master` branch of this repo and ran in sbt 1. `show core/package` and 2. `core/publishLocal` on my machine. When comparing the content of the jars, the `publish` one includes includes the wrong classfiles in the `scala/collection/` package, it's the classes of the standard library instead of those in the module.

Diff is here: https://gist.github.com/lrytz/96e397595a4be5fbfe7a9b80baf48f28/revisions

It seems the assumption mentioned here is not correct: https://github.com/scala/scala-parallel-collections/blob/ca1a2942816cca626738a71987f5009a433b1c4a/build.sbt#L31-L32

I think this is pretty risky, and we should probably disable OSGi support if noone knows a better solution. cc @SethTisue.

**Comment by SethTisue** [comment]
agree, let's do that. also wdyt about #80 which proposes going to version 1.0?

**Comment by lrytz** [comment]
Bumping to 1.0.0 sounds good 👍
